# Generated by Django 3.0.7 on 2021-05-05 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_no_of_client', models.IntegerField()),
                ('Trusted', models.IntegerField()),
                ('Locations', models.IntegerField()),
                ('Consulting_services', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('main_body_img', models.ImageField(upload_to='images')),
                ('title_body', models.CharField(max_length=256)),
                ('title_icon', models.ImageField(upload_to='icons')),
                ('trending_title', models.CharField(blank=True, max_length=20)),
                ('trending_image', models.ImageField(blank=True, upload_to='trending')),
                ('trending_discription', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=400)),
                ('time', models.TimeField()),
                ('meeting_number', models.IntegerField()),
                ('password', models.CharField(max_length=500)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
